/*
 * graph_horizon_engine — incremental output text decoder
 * Converts arbitrary generated bytes into valid UTF-8 deltas. It retains an
 * incomplete trailing code point for the next token, replaces irrecoverably
 * invalid bytes, and discards an incomplete suffix at a terminal boundary.
 * Cancellation likewise drops this request-owned buffer.
 */

#[derive(Default)]
pub(crate) struct TextDecoder {
    pending: Vec<u8>,
}

impl TextDecoder {
    pub(crate) fn push(&mut self, bytes: &[u8]) -> Option<String> {
        self.pending.extend_from_slice(bytes);
        let mut output = String::new();

        loop {
            match std::str::from_utf8(&self.pending) {
                Ok(text) => {
                    output.push_str(text);
                    self.pending.clear();
                    break;
                }
                Err(error) => {
                    let valid = error.valid_up_to();
                    let invalid = error.error_len();
                    if valid > 0 {
                        output.push_str(
                            std::str::from_utf8(&self.pending[..valid])
                                .expect("validated UTF-8 prefix"),
                        );
                        self.pending.drain(..valid);
                    }
                    let Some(invalid) = invalid else {
                        break;
                    };
                    // The invalid span cannot become valid with later bytes.
                    output.push('\u{FFFD}');
                    self.pending.drain(..invalid);
                }
            }
        }

        (!output.is_empty()).then_some(output)
    }

    pub(crate) fn finish(self) {
        // The pending bytes cannot form text on their own and were never emitted.
        // EOS therefore closes the valid prefix instead of turning it into an error.
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emits_only_complete_utf8() {
        let mut decoder = TextDecoder::default();
        assert_eq!(decoder.push(&[0xe2, 0x82]), None);
        assert_eq!(decoder.push(&[0xac, b'!']), Some("€!".into()));
        decoder.finish();
    }

    #[test]
    fn emits_an_emoji_split_across_byte_tokens_without_replacement() {
        let mut decoder = TextDecoder::default();
        assert_eq!(decoder.push(&[0xf0]), None);
        assert_eq!(decoder.push(&[0x9f, 0x8c]), None);
        assert_eq!(decoder.push(&[0x8d]), Some("🌍".into()));
        decoder.finish();
    }

    #[test]
    fn replaces_invalid_text_and_discards_incomplete_suffix() {
        let mut invalid = TextDecoder::default();
        assert_eq!(invalid.push(&[0xff, b'a']), Some("�a".into()));
        invalid.finish();

        let mut split = TextDecoder::default();
        assert_eq!(split.push(&[0xe2]), None);
        assert_eq!(split.push(b"!"), Some("�!".into()));
        split.finish();

        let mut incomplete = TextDecoder::default();
        assert_eq!(incomplete.push(&[0xe2]), None);
        incomplete.finish();
    }
}
