/*
 * Vulkan pipeline specification: maps every reachable kernel to its SPIR-V module and ABI without owning device state or resources.
 */
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum Kernel {
    MatmulF16,
    MatmulQ4KTiled,
    MatmulQ5K,
    MatmulQ6K,
    Logits,
    LogitsQ4K,
    LogitsQ5K,
    LogitsQ6K,
    EmbedF16,
    EmbedQ4K,
    EmbedQ5K,
    EmbedQ6K,
    RmsNormX,
    Rope,
    Residual,
    KvWrite,
    AttentionDecode,
    AttentionDecodeWide,
    AttentionDecode1024,
    AttentionDecodeGqaSplit,
    AttentionDecodeGqaInt8Split,
    AttentionDecodeGqaWave64Split,
    AttentionDecodeGqaReduce,
    AttentionDecodeGqaWave64Reduce,
    AttentionPrefill,
    AttentionPrefillWide,
    AttentionPrefillTiled,
    AttentionPrefillTiledCoopQk,
    AttentionPrefillMatrix2,
    AttentionPrefillMatrix2Q64,
    KvWriteInt8,
    AttentionDecodeInt8,
    AttentionPrefillInt8,
    Argmax,
    TopkPartial,
    SiluMul,
    MatmulQ4KBatchF16Out,
    MatmulQ6KBatchF16Out,
    MatmulQ4KCoopmatF16Out,
    MatmulQ4KCoopmatMetadataF16Out,
    MatmulQ4KMatrix2F16Out,
    MatmulQ6KCoopmatF16Out,
    MatmulQ6KMatrix2F16Out,
    QuantAQ8F16,
    MatmulQ4KMmvqF16Out,
    MatmulQ4KMmqBatchF16Out,
}

// Pipelines required on every supported Vulkan device. Optional variants are
// appended by the registry only after their capability checks pass.
pub(super) const BASE: &[Kernel] = &[
    Kernel::MatmulF16,
    Kernel::MatmulQ4KTiled,
    Kernel::MatmulQ5K,
    Kernel::MatmulQ6K,
    Kernel::Logits,
    Kernel::LogitsQ4K,
    Kernel::LogitsQ5K,
    Kernel::LogitsQ6K,
    Kernel::EmbedF16,
    Kernel::EmbedQ4K,
    Kernel::EmbedQ5K,
    Kernel::EmbedQ6K,
    Kernel::RmsNormX,
    Kernel::Rope,
    Kernel::Residual,
    Kernel::KvWrite,
    Kernel::AttentionDecode,
    Kernel::AttentionPrefill,
    Kernel::KvWriteInt8,
    Kernel::AttentionDecodeInt8,
    Kernel::AttentionPrefillInt8,
    Kernel::Argmax,
    Kernel::TopkPartial,
    Kernel::SiluMul,
    Kernel::MatmulQ4KBatchF16Out,
    Kernel::MatmulQ6KBatchF16Out,
];
#[cfg(feature = "vulkan-profile")]
impl Kernel {
    pub(crate) const fn name(self) -> &'static str {
        match self {
            Self::MatmulF16 => "matmul_f16",
            Self::MatmulQ4KTiled => "matmul_q4k_tiled",
            Self::MatmulQ5K => "matmul_q5k",
            Self::MatmulQ6K => "matmul_q6k",
            Self::Logits => "logits_f16",
            Self::LogitsQ4K => "logits_q4k",
            Self::LogitsQ5K => "logits_q5k",
            Self::LogitsQ6K => "logits_q6k",
            Self::EmbedF16 => "embed_f16",
            Self::EmbedQ4K => "embed_q4k",
            Self::EmbedQ5K => "embed_q5k",
            Self::EmbedQ6K => "embed_q6k",
            Self::RmsNormX => "rmsnorm_x",
            Self::Rope => "rope",
            Self::Residual => "residual",
            Self::KvWrite => "kv_write_f16",
            Self::AttentionDecode => "attention_decode",
            Self::AttentionDecodeWide => "attention_decode_wide",
            Self::AttentionDecode1024 => "attention_decode_1024",
            Self::AttentionDecodeGqaSplit => "attention_decode_gqa_split8_q4_vec4_wg256",
            Self::AttentionDecodeGqaInt8Split => "attention_decode_gqa_int8_split8_q4_vec4_wg256",
            Self::AttentionDecodeGqaWave64Split => "attention_decode_gqa_split4_q4_wave64_wg256",
            Self::AttentionDecodeGqaReduce => "attention_decode_gqa_reduce_q4_vec4",
            Self::AttentionDecodeGqaWave64Reduce => "attention_decode_gqa_reduce16_q4_wave64",
            Self::AttentionPrefill => "attention_prefill",
            Self::AttentionPrefillWide => "attention_prefill_wide",
            Self::AttentionPrefillTiled => "attention_prefill_tiled_phased_q8_kv64",
            Self::AttentionPrefillTiledCoopQk => "attention_prefill_tiled_fullmma_q16_kv64",
            Self::AttentionPrefillMatrix2 => "attention_prefill_matrix2_wg256_q32_kv64",
            Self::AttentionPrefillMatrix2Q64 => "attention_prefill_matrix2_wg128_q64_kv64",
            Self::KvWriteInt8 => "kv_write_int8",
            Self::AttentionDecodeInt8 => "attention_decode_int8",
            Self::AttentionPrefillInt8 => "attention_prefill_int8",
            Self::Argmax => "argmax",
            Self::TopkPartial => "topk_partial",
            Self::SiluMul => "silu_mul",
            Self::MatmulQ4KBatchF16Out => "matmul_q4k_batch_f16",
            Self::MatmulQ6KBatchF16Out => "matmul_q6k_batch_f16",
            Self::MatmulQ4KCoopmatF16Out => "matmul_q4k_coopmat_f16",
            Self::MatmulQ4KCoopmatMetadataF16Out => "matmul_q4k_coopmat_metadata_f16",
            Self::MatmulQ4KMatrix2F16Out => "matmul_q4k_matrix2_wg256_m128_n32_k128",
            Self::MatmulQ6KCoopmatF16Out => "matmul_q6k_coopmat_f16",
            Self::MatmulQ6KMatrix2F16Out => "matmul_q6k_matrix2_wg256_m64_n32_k128",
            Self::QuantAQ8F16 => "quant_a_q8_f16",
            Self::MatmulQ4KMmvqF16Out => "matmul_q4k_mmvq_f16",
            Self::MatmulQ4KMmqBatchF16Out => "matmul_q4k_mmq_batch_f16",
        }
    }
}

// SPIR-V bytes, storage-buffer binding count, and push-constant bytes.
pub(super) fn spec(kernel: Kernel) -> (&'static [u8], u32, u32) {
    macro_rules! spv {
        ($name:literal) => {
            include_bytes!(concat!(env!("OUT_DIR"), "/", $name, ".spv"))
        };
    }
    match kernel {
        Kernel::MatmulF16 => (spv!("matmul_fp16"), 3, 8),
        Kernel::MatmulQ4KTiled => (spv!("matmul_tiled"), 3, 8),
        Kernel::MatmulQ5K => (spv!("matmul_q5_k"), 3, 8),
        Kernel::MatmulQ6K => (spv!("matmul_q6_k"), 3, 8),
        Kernel::Logits => (spv!("logits"), 3, 8),
        Kernel::LogitsQ4K => (spv!("logits_q4_k"), 3, 8),
        Kernel::LogitsQ5K => (spv!("logits_q5_k"), 3, 8),
        Kernel::LogitsQ6K => (spv!("logits_q6_k"), 3, 8),
        Kernel::EmbedF16 => (spv!("embed_f16"), 2, 8),
        Kernel::EmbedQ4K => (spv!("embed_q4_k"), 2, 8),
        Kernel::EmbedQ5K => (spv!("embed_q5_k"), 2, 8),
        Kernel::EmbedQ6K => (spv!("embed_q6_k"), 2, 8),
        Kernel::RmsNormX => (spv!("rmsnorm_x"), 3, 8),
        Kernel::Rope => (spv!("rope"), 1, 44),
        Kernel::Residual => (spv!("residual"), 2, 4),
        Kernel::KvWrite => (spv!("kv_write"), 4, 8),
        Kernel::AttentionDecode => (spv!("attention_decode"), 4, 32),
        Kernel::AttentionDecodeWide => (spv!("attention_decode_wide"), 4, 32),
        Kernel::AttentionDecode1024 => (spv!("attention_decode_1024"), 4, 32),
        Kernel::AttentionDecodeGqaSplit => (spv!("attention_decode_gqa_split"), 5, 28),
        Kernel::AttentionDecodeGqaInt8Split => (spv!("attention_decode_gqa_int8_split"), 5, 32),
        Kernel::AttentionDecodeGqaWave64Split => (spv!("attention_decode_gqa_wave64_split"), 5, 32),
        Kernel::AttentionDecodeGqaReduce => (spv!("attention_decode_gqa_reduce"), 3, 28),
        Kernel::AttentionDecodeGqaWave64Reduce => {
            (spv!("attention_decode_gqa_wave64_reduce"), 3, 32)
        }
        Kernel::AttentionPrefill => (spv!("attention_prefill"), 4, 32),
        Kernel::AttentionPrefillWide => (spv!("attention_prefill_wide"), 4, 32),
        Kernel::AttentionPrefillTiled => (spv!("attention_prefill_tiled"), 4, 32),
        Kernel::AttentionPrefillTiledCoopQk => (spv!("attention_prefill_tiled_coopqk"), 4, 32),
        Kernel::AttentionPrefillMatrix2 => (spv!("attention_prefill_matrix2"), 4, 32),
        Kernel::AttentionPrefillMatrix2Q64 => (spv!("attention_prefill_matrix2_q64"), 4, 32),
        Kernel::KvWriteInt8 => (spv!("kv_write_int8"), 4, 16),
        Kernel::AttentionDecodeInt8 => (spv!("attention_decode_int8"), 4, 32),
        Kernel::AttentionPrefillInt8 => (spv!("attention_prefill_int8"), 4, 36),
        Kernel::Argmax => (spv!("argmax"), 2, 4),
        Kernel::TopkPartial => (spv!("topk_partial"), 2, 8),
        Kernel::SiluMul => (spv!("silu_mul"), 3, 4),
        Kernel::MatmulQ4KBatchF16Out => (spv!("matmul_q4_k_batch_f16"), 3, 12),
        Kernel::MatmulQ6KBatchF16Out => (spv!("matmul_q6_k_batch_f16"), 3, 12),
        Kernel::MatmulQ4KCoopmatF16Out => (spv!("matmul_q4_k_coopmat_f16out"), 3, 12),
        Kernel::MatmulQ4KCoopmatMetadataF16Out => {
            (spv!("matmul_q4_k_coopmat_metadata_f16out"), 3, 12)
        }
        Kernel::MatmulQ4KMatrix2F16Out => (spv!("matmul_q4_k_matrix2_f16out"), 3, 12),
        Kernel::MatmulQ6KCoopmatF16Out => (spv!("matmul_q6_k_coopmat_f16out"), 3, 12),
        Kernel::MatmulQ6KMatrix2F16Out => (spv!("matmul_q6_k_matrix2_f16out"), 3, 12),
        Kernel::QuantAQ8F16 => (spv!("quant_a_q8_f16"), 3, 4),
        Kernel::MatmulQ4KMmvqF16Out => (spv!("matmul_q4_k_mmvq_f16out"), 4, 8),
        Kernel::MatmulQ4KMmqBatchF16Out => (spv!("matmul_q4_k_mmq_batch_f16"), 4, 12),
    }
}
